### PR TITLE
Upgrade `pulumi-gitlab` to v6

### PR DESCRIPTION
**Pull request by aq17**
Part of https://github.com/pulumi/pulumi-gitlab/pull/282

### CODE REVIEW

**Review by iwahbe — CHANGES_REQUESTED** [review]
I don't see a release for v6 in pulumi-gitlab, and the linked issue is closed. Do we still want to merge this?

**Comment by aq17** [comment]
@iwahbe my bad, it should be this link https://github.com/pulumi/pulumi-gitlab/pull/282.

**Review by iwahbe — APPROVED** [review]
We need to actually tag the v6 release in pulumi-gitlab. Can we do that now?

**Comment by aq17** [comment]
Yes https://github.com/pulumi/pulumi-gitlab/actions/runs/5157658368

**Pull request merged**
