### PR TITLE
Updating `pulumi-java-gen` to current latest v0.9.5

### PR DESCRIPTION
**Pull request by ringods**
I'm trying to get `ci-mgmt` working again for 3rd party providers. This PR is a first fix to get closer to that target.

Updating the version of `pulumi-java-gen` to current latest v0.9.5. The main fix needed for 3rd party providers is the generation of missing fields in the gradle build file added in [v0.9.4](https://github.com/pulumi/pulumi-java/releases/tag/v0.9.4)

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
Looks great to me ... would like someone from the previous Ecosystem team to weigh in on if there was any reason we were still using a very old version. cc: @iwahbe @guineveresaenger @t0yv0

**Comment by iwahbe** [comment]
> Looks great to me ... would like someone from the previous Ecosystem team to weigh in on if there was any reason we were still using a very old version. cc: @iwahbe @guineveresaenger @t0yv0

We were concerned that different versions of java have different user APIs (https://github.com/pulumi/pulumi-java/pull/704), so upgrading is a breaking change. I believe that Java is still in beta, so we could take the breaking change, I'm not sure if we want to.

CC @mikhailshilkov

**Comment by ringods** [comment]
@iwahbe if I track the actual changes made for https://github.com/pulumi/pulumi-java/issues/704, I notice (at first sight) that the versions `getId()` and `getUrn()` are still there but marked as `deprecated`. `id()` and `urn()` are added as the preferred methods.

* Resource - https://github.com/pulumi/pulumi-java/pull/766/files#diff-1ca5d6329be07370dac1f25ec7daf4528587822f0ad921cf537fbbdabf1c8021
* CustomResource - https://github.com/pulumi/pulumi-java/pull/766/files#diff-e7295d017481ef28c81cc4ab9b921050453ba304806c93b7ec4b1a49de58299e


The removal of the old `get` versions is till an open issue tracked as https://github.com/pulumi/pulumi-java/issues/769
This keeps the backwards compatibility for now.

**Review by iwahbe — APPROVED** [review]
LGTM

**Comment by t0yv0** [comment]
This can't be merged, this will break everything.

**Comment by t0yv0** [comment]
A little bit more context: it's a laudable goal to upgrade every provider to the latest Java version as well as build automation that keeps the latest Java version up-to-date. However, doing this in one PR will currently disrupt @pulumi/providers ability to operate the ci-mgmt build farm. The reason is a technicality - every night the changes to build workflows roll out across all ci-mgmt providers, and they stand up auto-merge PRs. AFAIK these auto-merge PRs do not actually regenerate sdk code, and upgrading Java will cause the PR checks to fail. Moreover, it will block any further PRs to ci-mgmt to automatically rollout across the provider repositories.

I would like to see a non-breaking course of action pursued here either:

1. The automated PRs are extended to automatically regenerate SDKs

2. The change is pursued provider-by-provider in a manual fashion one by one, and the SDKs are regenerated on a per-provider basis

3. The change is pursued in a manual fashion for all providers at once but a maintenance window is announced to the providers team explaining the context and the dates when the build farm will be inoperable

**Review by t0yv0 — CHANGES_REQUESTED** [review]
Appears to be unsafe, see comment above.

**Comment by ringods** [comment]
@t0yv0 I understand the impact. However, I would still like to see this change land in this repository. Is there anything I can help out with to recreate smaller PRs in line with the 1-by-1 approach?

**Comment by t0yv0** [comment]
@ringods absolutely if you have cycles to pursue 1, 2, or 3 that's wonderful. LMK if you need any more detail.

**Comment by ringods** [comment]
Will redo in smaller chunks.

**Pull request closed without merging**
