### PR TITLE
Refactor artifact cleanup

### PR DESCRIPTION
**Pull request by guineveresaenger**
This pull request removes the `artifact-cleanup.yml` Workflow from all managed providers.
Instead, we will use the `retention-days` [feature](https://github.com/marketplace/actions/upload-a-build-artifact#retention-period) of the `upload-artifact` Action to have artifacts expire after 30 days.
Previously, we ran the artifact cleanup Workflow on a cron that would remove all artifacts older than 30 days.
With this change, we are setting artifacts to expire after 30 days instead of the default 90 days that `upload-artifact` provides. 
This is a very likely fix for https://github.com/pulumi/pulumi-azure-native/issues/2558 and https://github.com/pulumi/pulumi-kubernetes/issues/2499, et al, since the Action we used in `artifact-cleanup.yml` caused a secondary rate limit error.
Related: https://github.com/pulumi/pulumi-aws/pull/2649.
h/t to @aq17 for finding this neat feature of `upload-artifact` :heart:

- Remove artifact cleanup cron and set retention-days to 30 on Upload Artifact job itself
- Regenerate tf providers
- Native providers: Remove artifact cleanup workflow and add retention-days to upload-artifacts job
- Generate native provider CI

### CODE REVIEW

**Comment by guineveresaenger** [comment]
for automation:

Fixes https://github.com/pulumi/pulumi-azure-native/issues/2558
Fixes https://github.com/pulumi/pulumi-kubernetes/issues/2499

**Review by iwahbe — APPROVED** [review]

**Comment by guineveresaenger** [comment]
@iwahbe based on [feedback from @thomas11](https://github.com/pulumi/pulumi-aws/pull/2649#discussion_r1277080139) I removed the retention days form any workflows triggered by tags. We will keep release and prerelease artifacts for the default 90 days.

**Comment by iwahbe** [comment]
> @iwahbe based on [feedback from @thomas11](https://github.com/pulumi/pulumi-aws/pull/2649#discussion_r1277080139) I removed the retention days from any workflows triggered by tags. We will keep release and prerelease artifacts for the default 90 days.

That doesn't sound right to me. We are able to access release artifacts that are older than 90 days. This is the [pulumi-aws v5.18.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.18.0), released mid-october of 2022. All the released artifacts are accessible.

The artifacts as stored as part of the [release action](https://github.com/pulumi/pulumi-aws/actions/runs/3279883393) are inaccessible, but that doesn't matter. We don't expect users to consume artifacts from of the release action, just the actual release.

I think a 30 day retention period is fine. There isn't a clear reason to special case these workflow artifacts compared to other workflow artifacts.

CC @thomas11 @mikhailshilkov

**Review by iwahbe — COMMENTED** [review]
> @iwahbe based on [feedback from @thomas11](https://github.com/pulumi/pulumi-aws/pull/2649#discussion_r1277080139) I removed the retention days from any workflows triggered by tags. We will keep release and prerelease artifacts for the default 90 days.

That doesn't sound right to me. We are able to access release artifacts that are older than 90 days. This is the [pulumi-aws v5.18.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.18.0), released mid-october of 2022. All the released artifacts are accessible.

The artifacts as stored as part of the [release action](https://github.com/pulumi/pulumi-aws/actions/runs/3279883393) are inaccessible, but that doesn't matter. We don't expect users to consume artifacts from of the release action, just the actual release.

I think a 30 day retention period is fine. There isn't a clear reason to special case these workflow artifacts compared to other workflow artifacts.

CC @thomas11 @mikhailshilkov

**Pull request merged**
