### PR TITLE
Install .NET 6 on runners

### PR DESCRIPTION
**Pull request by t0yv0**
Anticipating the upgrade to .NET6 , ensure that it is available on runners.

### CODE REVIEW

**Comment by t0yv0** [comment]
I've tested this change on pulumi-tls. Full upgrade instructions in https://github.com/pulumi/home/issues/2531

**Review by lblackstone — APPROVED** [review]
Just to make sure I understand the change, this adds .NET 6.0 to the test matrix, but doesn't change the provider dependencies?

**Comment by t0yv0** [comment]
This is a preparatory change it should be no-op for existing code. It makes sure .NET 6.0 is available in the GHA environment. Once this is applied, providers may continue upgrading to newer pulumi/pkg that will actually update provider .NET SDK dependency to .NET 6.0.

**Comment by t0yv0** [comment]
Thanks for the quick review @lblackstone

**Pull request merged**
